### PR TITLE
RefactorDatabase

### PR DESCRIPTION
**Pull request by jeffreykat**
Database with Room is almost complete. Bugs in fetching data based on ID

### CODE REVIEW

**Comment by jeffreykat** [comment]
There is still one bug that is causing problems in the SubDetailsActivity and CreateSubActivity. Retrieving from the database based on ID always returns null, even if the data is there. I'm trying to figure it out, but maybe one of you will see the problem before me.

**Comment by Bradford-Wong** [comment]
I think I see the problem... but I'm not sure how to fix it. In the doInBackground() of  InsertSubmissionAsyncTask (LocalRepository.java), the dao.insertSubmission(submissionTables[0]); actually calls a function that returns the ID. So we need to get the ID that it returns and somehow get it back to the CreateSubActivity.  I've seen a couple of examples where they get the data from the onPostExecute() using an interface, but their cases are a little bit different since the class that calls the AsyncTask is the activity itself. Here are some examples: https://stackoverflow.com/questions/13815807/return-value-from-asynctask-class-onpostexecute-method https://stackoverflow.com/questions/4489399/asynctask-where-does-the-return-value-of-doinbackground-go. 

I'm not sure if this helped, but I hope it gives you an idea.

**Comment by Bradford-Wong** [comment]
How important is it that we get the refactor in before the code freeze? My replies feature is almost complete, but I've been holding off on it because I've been waiting for the refactor. I would like to get the replies feature in before the freeze, so would you be ok with me putting up a pull request for it using the current database and then merging the refactor after the code freeze?

**Comment by jeffreykat** [comment]
Fix needed on new branch: associate user with submission before submit

**Pull request merged**
